"""empty message

Revision ID: 22e8835dee8c
Revises: 8cad66788a3b
Create Date: 2019-06-19 13:54:05.849717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e8835dee8c'
down_revision = '8cad66788a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('images', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'images')
    # ### end Alembic commands ###
