"""empty message

Revision ID: b281b913984a
Revises: bb8ed89e1077
Create Date: 2019-06-06 14:19:08.680186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b281b913984a'
down_revision = 'bb8ed89e1077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
